[repository]
name = "dynamic-cursors"
authors = "Virt"
commit_pins = [
    # v Hyprland                                  v hypr-dynamic-cursors
    ["918d8340afd652b011b937d29d5eea0be08467f5", "f0409be76564171a97a792deabab3bd0528fe40c"], # v0.41.2
    ["9a09eac79b85c846e3a865a9078a3f8ff65a9259", "ddfea3a29c9badf6dabe12be86e4c5ba6d5507ad"], # v0.42.0
    ["0f594732b063a90d44df8c5d402d658f27471dfe", "ddfea3a29c9badf6dabe12be86e4c5ba6d5507ad"], # v0.43.0
    ["0c7a7e2d569eeed9d6025f3eef4ea0690d90845d", "3ff4c2a053f7673b3b8cd45ada0886cbda13ebcc"], # v0.44.0
    ["4520b30d498daca8079365bdb909a8dea38e8d55", "3ff4c2a053f7673b3b8cd45ada0886cbda13ebcc"], # v0.44.1
]

[dynamic-cursors]
description = "make your cursors more realistic"
authors = ["Virt"]
output = "out/dynamic-cursors.so"
build = [
    "make all",
]
